name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  ANSIBLE_USER: 'ansible'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test building Dockerfile.
      run: docker build -t docker-ansible .

    - name: Test running the container.
      run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

    - name: Verify that `ansible` user exists and is a sudoer
      run: docker exec --tty test-container env TERM=xterm sudo -u ${{ env.ANSIBLE_USER }} sudo -v

    - name: Verify Ansible is available in the container.
      run: docker exec --tty test-container env TERM=xterm ansible --version
